// ===----------------------------------------------------------------------===//
//
// This source file is part of the swift-linter open source project
//
// Copyright (c) 2026 Coen ten Thije Boonkkamp and the swift-linter project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
//
// ===----------------------------------------------------------------------===//

public import JSON

/// A serializable snapshot of a per-package linter configuration.
///
/// `Lint.Manifest` is the boundary type that crosses the
/// `swift-manifest` subprocess gap. The user's `Lint.swift`
/// declares `let manifest: Lint.Manifest = …` at file scope; the
/// driver shim — generated by ``swift-manifest`` — JSON-encodes
/// the value to a known output path; the parent linter decodes
/// the JSON and reconstructs a runtime ``Lint/Configuration``.
///
/// ## Phase 2 v2 scope
///
/// - ``enabledRuleIDs`` — string IDs (matching ``Lint/Rule/ID``'s
///   raw value) of rules to activate.
/// - ``excludedPaths`` — package-specific path-prefix exclusions
///   (the linter's source walker already excludes `.build/` etc.;
///   this list adds extras).
///
/// Severity overrides, custom rules, and parent-manifest
/// inheritance are deferred to v3 once the single-file
/// evaluation surface is proven.
extension Lint {
    public struct Manifest: Sendable {
        public let enabledRuleIDs: [Swift.String]
        public let excludedPaths: [Swift.String]

        public init(
            enabledRuleIDs: [Swift.String],
            excludedPaths: [Swift.String] = []
        ) {
            self.enabledRuleIDs = enabledRuleIDs
            self.excludedPaths = excludedPaths
        }
    }
}

// MARK: - JSON.Serializable

extension Lint.Manifest: JSON.Serializable {
    public static func serialize(_ value: Self) -> JSON {
        [
            "enabledRuleIDs": .array(value.enabledRuleIDs.map { .string($0) }),
            "excludedPaths": .array(value.excludedPaths.map { .string($0) })
        ]
    }

    public static func deserialize(_ json: JSON) throws(JSON.Error) -> Self {
        Self(
            enabledRuleIDs: try [Swift.String](json: json["enabledRuleIDs"]),
            excludedPaths: try [Swift.String](json: json["excludedPaths"])
        )
    }
}
