// ===----------------------------------------------------------------------===//
//
// This source file is part of the swift-linter open source project
//
// Copyright (c) 2026 Coen ten Thije Boonkkamp and the swift-linter project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
//
// ===----------------------------------------------------------------------===//

public import File_System
public import JSON
public import Linter_Primitives

/// A serializable snapshot of a per-package linter configuration.
///
/// `Lint.Manifest` is the boundary type that crosses the
/// `swift-manifest` subprocess gap. The user's `Lint.swift`
/// declares `let manifest: Lint.Manifest = …` at file scope; the
/// driver shim — generated by ``swift-manifest`` — JSON-encodes
/// the value to a known output path; the parent linter decodes
/// the JSON and reconstructs a runtime ``Lint/Configuration``.
///
/// ## Phase 2 v2 scope
///
/// - ``rules`` Property.View — leaves ``Rules/enabled`` /
///   ``Rules/disabled`` surface the typed `Lint.Rule.ID` sets of
///   rules to activate / deactivate at this manifest's layer.
///   Mixing rule IDs with file IDs, config keys, or other String
///   identifiers is rejected at the type system, not at runtime.
///   Construction at consumer call sites uses the
///   `ExpressibleByStringLiteral` conformance shipped by
///   `swift-tagged-primitives`'s standard-library-integration:
///   `let id: Lint.Rule.ID = "unchecked_call_site"`.
///   Layered with parent inheritance: a child manifest's
///   ``Rules/disabled`` overrides a parent's ``Rules/enabled`` for the
///   same ID via the Configuration layer's per-TYPE override semantics.
/// - ``excluded`` — package-specific path-prefix exclusions
///   (the linter's source walker already excludes `.build/` etc.;
///   this list adds extras). Stored as `[File.Path]` from
///   `swift-file-system` — `Paths.Path` is Copyable + Sendable +
///   Hashable, fits stdlib `Array`, and provides typed path values
///   end-to-end. Consumer-authored manifests construct entries via
///   `try File.Path("Tests/Fixtures")` at the manifest call site.
///
/// ## JSON wire format
///
/// The JSON wire format is flat (`enabled`, `disabled`, `excluded`
/// keys at the document root) — rule-IDs as bare strings, path values
/// via `path.description`. The serializer unwraps each
/// `Lint.Rule.ID` to its raw `String`; the deserializer wraps each
/// raw `String` back into a `Lint.Rule.ID`. Invalid path strings
/// surface as `JSON.Error.typeMismatch`. A v2 consumer's Lint.swift
/// authored against the typed surface produces wire-compatible output.
///
/// Tagged-generic `JSON.Serializable` conformance is NOT introduced
/// here. The natural home (swift-linter-primitives at L1) cannot
/// accept the JSON dependency without a layering violation
/// (JSON is L3); the manual unwrap below is the v2 workaround.
/// A future ecosystem package (e.g., `swift-tagged-json`) may host
/// the generic conformance properly.
///
/// Severity overrides and user-authored custom rules are deferred
/// to v3. Parent-manifest inheritance lands in v2 alongside
/// rule disables; the driver in
/// ``Lint/Driver/configuration(at:manifestOverride:onMissingLinterPath:)``
/// walks the parent chain and folds each manifest into a layered
/// ``Lint/Configuration`` with `inheriting:` parent.
extension Lint {
    public struct Manifest: Sendable, Hashable {
        /// Rule-related leaves (``Rules/enabled`` / ``Rules/disabled``)
        /// surfaced via the institute's larger.smaller Property.View
        /// shape. Reads as `manifest.rules.enabled` /
        /// `manifest.rules.disabled` mirroring
        /// ``Lint/Configuration/Rules``.
        public let rules: Rules

        /// Package-specific path-prefix exclusions.
        public let excluded: [File.Path]

        public init(
            enabled: Set<Lint.Rule.ID> = [],
            disabled: Set<Lint.Rule.ID> = [],
            excluded: [File.Path] = []
        ) {
            self.rules = Rules(enabled: enabled, disabled: disabled)
            self.excluded = excluded
        }
    }
}

extension Lint.Manifest {
    /// Property.View on ``Lint/Manifest`` for rule-related leaves.
    public struct Rules: Sendable, Hashable {
        /// Rule IDs to activate at this manifest's layer.
        public let enabled: Set<Lint.Rule.ID>

        /// Rule IDs to deactivate at this manifest's layer. Layered
        /// with parent inheritance per the Configuration's
        /// ``Lint/Configuration/Rules/effective`` override semantics.
        public let disabled: Set<Lint.Rule.ID>

        public init(
            enabled: Set<Lint.Rule.ID> = [],
            disabled: Set<Lint.Rule.ID> = []
        ) {
            self.enabled = enabled
            self.disabled = disabled
        }
    }
}

// MARK: - JSON.Serializable

extension Lint.Manifest: JSON.Serializable {
    public static func serialize(_ value: Self) -> JSON {
        [
            "enabled": .array(value.rules.enabled.map { .string($0.underlying) }),
            "disabled": .array(value.rules.disabled.map { .string($0.underlying) }),
            "excluded": .array(value.excluded.map { .string($0.description) })
        ]
    }

    public static func deserialize(_ json: JSON) throws(JSON.Error) -> Self {
        // F-A3.1 (audit `Research/2026-05-12-typed-primitive-adoption-audit.md`):
        // typed `Set<Lint.Rule.ID>` locals replace the prior
        // `[Swift.String] enabledRaw / disabledRaw` bindings. Wire
        // format remains bare strings on the JSON side; the typed lift
        // happens immediately at the deserialization boundary so every
        // downstream reference operates on the Set surface.
        let enabledIDs: [Lint.Rule.ID] = try [Swift.String](json: json["enabled"]).map { Lint.Rule.ID($0) }
        let disabledIDs: [Lint.Rule.ID] = try [Swift.String](json: json["disabled"]).map { Lint.Rule.ID($0) }
        let enabled = Set(enabledIDs)
        let disabled = Set(disabledIDs)
        let excludedRaw = try [Swift.String](json: json["excluded"])
        let excluded: [File.Path] = try excludedRaw.map { (string: Swift.String) throws(JSON.Error) -> File.Path in
            do throws(Paths.Path.Error) {
                return try File.Path(string)
            } catch {
                throw JSON.Error.typeMismatch(
                    expected: "File.Path string",
                    got: "invalid path: \(string)"
                )
            }
        }
        return Self(
            enabled: enabled,
            disabled: disabled,
            excluded: excluded
        )
    }
}
