// ===----------------------------------------------------------------------===//
//
// This source file is part of the swift-linter open source project
//
// Copyright (c) 2026 Coen ten Thije Boonkkamp and the swift-linter project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
//
// ===----------------------------------------------------------------------===//

public import File_System
public import JSON

/// A serializable snapshot of a per-package linter configuration.
///
/// `Lint.Manifest` is the boundary type that crosses the
/// `swift-manifest` subprocess gap. The user's `Lint.swift`
/// declares `let manifest: Lint.Manifest = …` at file scope; the
/// driver shim — generated by ``swift-manifest`` — JSON-encodes
/// the value to a known output path; the parent linter decodes
/// the JSON and reconstructs a runtime ``Lint/Configuration``.
///
/// ## Phase 2 v2 scope
///
/// - ``enabledRuleIDs`` — typed `Lint.Rule.ID` (Tagged<Lint.Rule,
///   Swift.String>) of rules to activate at this manifest's layer.
///   Mixing rule IDs with file IDs, config keys, or other String
///   identifiers is rejected at the type system, not at runtime.
///   Construction at consumer call sites uses the
///   `ExpressibleByStringLiteral` conformance shipped by
///   `swift-tagged-primitives`'s standard-library-integration:
///   `let id: Lint.Rule.ID = "unchecked_call_site"`.
/// - ``disabledRuleIDs`` — typed `Lint.Rule.ID`s to deactivate at
///   this layer. Layered with parent inheritance: a child manifest's
///   `disabledRuleIDs` overrides a parent's `enabledRuleIDs` for the
///   same ID via the Configuration layer's per-TYPE override
///   semantics.
/// - ``excludedPaths`` — package-specific path-prefix exclusions
///   (the linter's source walker already excludes `.build/` etc.;
///   this list adds extras). Stored as `[File.Path]` from
///   `swift-file-system` — `Paths.Path` is Copyable + Sendable +
///   Hashable, fits stdlib `Array`, and provides typed path values
///   end-to-end. Consumer-authored manifests construct entries via
///   `try File.Path("Tests/Fixtures")` at the manifest call site.
///
/// ## JSON wire format
///
/// Despite the typed Swift API surface, the JSON wire format
/// remains rule-IDs as bare strings — the serializer unwraps each
/// `Lint.Rule.ID` to its raw `String` and the deserializer wraps
/// each raw `String` back into a `Lint.Rule.ID`. Path values are
/// serialized via `path.description` (CustomStringConvertible) and
/// re-validated on deserialization via `try File.Path(string)`;
/// invalid path strings surface as `JSON.Error.typeMismatch`. A
/// v2 consumer's Lint.swift authored against the typed surface
/// produces wire-compatible output.
///
/// Tagged-generic `JSON.Serializable` conformance is NOT introduced
/// here. The natural home (swift-linter-primitives at L1) cannot
/// accept the JSON dependency without a layering violation
/// (JSON is L3); the manual unwrap below is the v2 workaround.
/// A future ecosystem package (e.g., `swift-tagged-json`) may host
/// the generic conformance properly.
///
/// Severity overrides and user-authored custom rules are deferred
/// to v3. Parent-manifest inheritance lands in v2 alongside
/// `disabledRuleIDs`; the driver in
/// ``Lint/Driver/resolveConfiguration(consumerPackageRoot:)``
/// walks the parent chain and folds each manifest into a layered
/// ``Lint/Configuration`` with `inheriting:` parent.
extension Lint {
    public struct Manifest: Sendable {
        public let enabledRuleIDs: [Lint.Rule.ID]
        public let disabledRuleIDs: [Lint.Rule.ID]
        public let excludedPaths: [File.Path]

        public init(
            enabledRuleIDs: [Lint.Rule.ID],
            disabledRuleIDs: [Lint.Rule.ID] = [],
            excludedPaths: [File.Path] = []
        ) {
            self.enabledRuleIDs = enabledRuleIDs
            self.disabledRuleIDs = disabledRuleIDs
            self.excludedPaths = excludedPaths
        }
    }
}

// MARK: - JSON.Serializable

extension Lint.Manifest: JSON.Serializable {
    public static func serialize(_ value: Self) -> JSON {
        [
            "enabledRuleIDs": .array(value.enabledRuleIDs.map { .string($0.underlying) }),
            "disabledRuleIDs": .array(value.disabledRuleIDs.map { .string($0.underlying) }),
            "excludedPaths": .array(value.excludedPaths.map { .string($0.description) })
        ]
    }

    public static func deserialize(_ json: JSON) throws(JSON.Error) -> Self {
        let enabledRaw = try [Swift.String](json: json["enabledRuleIDs"])
        let disabledRaw = try [Swift.String](json: json["disabledRuleIDs"])
        let excludedRaw = try [Swift.String](json: json["excludedPaths"])
        let excludedPaths: [File.Path] = try excludedRaw.map { (string: Swift.String) throws(JSON.Error) -> File.Path in
            do {
                return try File.Path(string)
            } catch {
                throw JSON.Error.typeMismatch(
                    expected: "File.Path string",
                    got: "invalid path: \(string)"
                )
            }
        }
        return Self(
            enabledRuleIDs: enabledRaw.map { Lint.Rule.ID($0) },
            disabledRuleIDs: disabledRaw.map { Lint.Rule.ID($0) },
            excludedPaths: excludedPaths
        )
    }
}
